### ISSUE TITLE
show ivyReport shows incorrect directory

### ISSUE THREAD

**Issue by anuccio1** [jrudolph/sbt-dependency-graph#150]
sample repo: https://github.com/anuccio1/sbt-test

when `show ivyReport` is run, this is shown:
`sbt-test/target/scala-2.11/resolution-cache/reports/com.alex.test-alex-test_2.11-compile.xml`
when really the file was written to 
`sbt-test/target/resolution-cache/reports/com.alex.test-alex-test_2.11-compile.xml`

**Comment by jrudolph** [comment]
Seems that the directory was changed in 0.13.16 (in https://github.com/sbt/sbt/commit/ff017eb475fbf18b8066125596bcd1a8cd8fb3ff#diff-6373e7f7122325e753b75fe1cc76ff5fR1419) and already "fixed" here. So it should work for sbt > 0.13.16.

We could fix it by retrieving the right directory from the `ivyConfiguration` key instead of building the directory ourselves.
